// DOCX round-trip fidelity corpus + harness (P0.5 / QA-09 / DXS-17).
//
// For every fixture in src/docx/__fixtures__/corpus/ (generated by
// scripts/generate-docx-corpus.mjs), exercises two round trips:
//   - "no-op": loadDocx -> saveDocx -> re-load, no changes.
//   - "trivial-edit": loadDocx -> insert text at a fixture-specific position
//     via the editor command API -> saveDocx -> re-load.
//
// Both assert: the saved package is a valid zip whose XML/rels parts are
// all well-formed; every internal relationship resolves to a part that
// exists and has a content type; every part Atlas doesn't intentionally
// rewrite is byte-identical to the original; and a structural fingerprint of
// word/document.xml (element counts plus attribute-level values — see
// `documentStructuralCounts`'s own doc comment) is unchanged.
//
// A fixture+mode already known to fail (see the findings register at
// .sisyphus/plans/atlas-phase3-findings-register.md) is encoded as
// `it.fails` with its finding id in the title, so this suite is green today
// and flips red — telling whoever fixed it to promote the case back to
// `it` — the moment the underlying bug is fixed.
import { describe, expect, it } from 'vitest'

import { applyCommand } from '../editor'
import type { Position } from '../editor'
import { loadDocx, saveDocx } from '../index'
import type { DocxBundle } from '../index'
import type { Paragraph } from '../model'
import {
  documentStructuralCounts,
  documentXmlOf,
  findMalformedXmlParts,
  findPassthroughMismatches,
  findRelationshipProblems,
  listCorpusFixtureIds,
  loadRawPackage,
  ownedPartPaths,
  readCorpusFixture,
  textOf,
} from './corpusRoundtripHelpers'

const FIXTURE_IDS = [
  'comments-with-reply',
  'content-control-alternate-content',
  'custom-xml-part',
  'embedded-fonts',
  'footnotes-endnotes',
  'header-footer-page-numbers',
  'hyperlinks-bookmarks',
  'image-anchored-floating',
  'image-crop-rotation-flip',
  'image-emf-wmf',
  'image-inline',
  'lists-bullets-numbered',
  'macro-enabled-vba-project',
  'math-omml',
  'page-borders-columns',
  'plain-paragraphs-styles',
  'rtl-text',
  'section-breaks',
  'table-fixed-grid-merged-cells',
  'table-styled-banded',
  'tracked-changes-insert-delete',
  'watermark-header',
] as const

type FixtureId = (typeof FIXTURE_IDS)[number]
type RoundtripMode = 'no-op' | 'trivial-edit'

// Every fixture's body starts with one paragraph containing one plain run
// (see scripts/generate-docx-corpus.mjs's `introParagraph`) — this is the
// generic fallback position, used only for the handful of fixtures whose
// actual signature construct sits in a paragraph the editor's `insert-text`
// command cannot target at all (see the "insert-text can't reach every
// construct" describe block below).
const INTRO_PARAGRAPH_START: Position = {
  paragraphPath: [0, 0],
  runIndex: 0,
  charOffset: 0,
}

/**
 * Per-fixture trivial-edit insertion point, aimed at (or, where the editor
 * can't reach the construct itself, immediately adjacent to) the construct
 * each fixture exists to exercise — see TEST-1 in the phase4/b4-corpus-tests
 * task brief. Before this map, every fixture reused `INTRO_PARAGRAPH_START`
 * (paragraph 0, the generic "Fixture: <name>." intro line generated by
 * `introParagraph` in scripts/generate-docx-corpus.mjs), so the trivial-edit
 * round trip never actually touched the feature under test — e.g. for
 * `tracked-changes-insert-delete.docx`, the real `w:ins`/`w:del` content is
 * in paragraph 1, not paragraph 0.
 *
 * All `paragraphPath`s are written in full `[sectionIndex, ...blockPath]`
 * form (see `resolveParagraphPath` in src/docx/editor/commands.ts) rather
 * than relying on its single-element shorthand, so a path naming a non-zero
 * section (`section-breaks`) reads the same way as the rest.
 *
 * Every position below was hand-verified (see the finding note where
 * present) against src/docx/editor/commands.ts's `getEditableRuns`: it
 * flattens a paragraph's `run`/`hyperlink`/`ins-revision`/`del-revision`
 * children into one ordered list of editable runs (so `runIndex` addresses
 * *that* flattened list, not `paragraph.children` directly), and rejects the
 * whole paragraph — throwing out of `applyCommand` — the instant it meets
 * any other child kind (a bookmark, comment range/reference, footnote/
 * endnote reference, field, or a bare `w:oMath` parsed as an `UnknownNode`).
 */
const EDIT_POSITIONS: Readonly<Record<FixtureId, Position>> = {
  // Comment ranges/references are direct paragraph children `getEditableRuns`
  // doesn't handle, so paragraph 1 (the one actually wrapped in
  // `w:commentRangeStart`/`End`) rejects `insert-text` outright — see the
  // "editor limitation" describe block below, which proves this. Falls back
  // to the intro paragraph; there is no other paragraph in this fixture.
  'comments-with-reply': INTRO_PARAGRAPH_START,
  // Paragraph 1 is the `w:sdt` content control's own paragraph (the `w:sdt`
  // wrapping doesn't change how it parses into the block model — it's a
  // plain one-run paragraph), so this lands squarely inside the content
  // control. (The following `mc:AlternateContent` paragraph is a separate,
  // deliberately untouched signature construct — its middle run's `w:drawing`
  // isn't plain text, so it isn't `insert-text`-editable either.)
  'content-control-alternate-content': { paragraphPath: [0, 1], runIndex: 0, charOffset: 5 },
  // The custom XML part (customXml/item1.xml) is an unreferenced
  // package-level part with no in-body construct to aim at — paragraph 1 is
  // this fixture's only real content.
  'custom-xml-part': { paragraphPath: [0, 1], runIndex: 0, charOffset: 2 },
  // Paragraph 1's run carries `font: 'Atlas Embedded Font'` — the actual
  // embedded-font reference under test.
  'embedded-fonts': { paragraphPath: [0, 1], runIndex: 0, charOffset: 7 },
  // Paragraph 1 carries the footnote/endnote reference runs directly as
  // paragraph children, which `getEditableRuns` doesn't handle (a run whose
  // only child is a `footnote-reference`/`endnote-reference` isn't
  // text-gettable) — see the "editor limitation" describe block below.
  // Falls back to the intro paragraph.
  'footnotes-endnotes': INTRO_PARAGRAPH_START,
  // Paragraph 1 is the only body paragraph under the watermark-free header;
  // the header/footer parts themselves aren't reachable through this
  // command's body-only `paragraphPath` addressing (header/footer text is
  // edited through a separate API — see src/docx/editor/headerFooter.ts).
  'header-footer-page-numbers': { paragraphPath: [0, 1], runIndex: 0, charOffset: 4 },
  // Paragraph 1's runs flatten to [run "Jump to the ", hyperlink-run "target
  // section", run " below, or visit ", hyperlink-run "an external site", run
  // "."] — runIndex 1 lands inside the *internal* hyperlink's own run text
  // (the one whose target is the bookmark in paragraph 2), splitting a
  // hyperlink run rather than a plain one.
  'hyperlinks-bookmarks': { paragraphPath: [0, 1], runIndex: 1, charOffset: 3 },
  // Paragraph 1 holds the floating/anchored image as a single atomic
  // `drawing` run (zero-width in the editor's run-flattening, so charOffset
  // must be 0) — inserting here splices new text right at the image's own
  // position, immediately adjacent to its anchor/wrap properties.
  'image-anchored-floating': { paragraphPath: [0, 1], runIndex: 0, charOffset: 0 },
  // Paragraph 1's single atomic run holds the cropped/rotated/flipped image.
  'image-crop-rotation-flip': { paragraphPath: [0, 1], runIndex: 0, charOffset: 0 },
  // Paragraph 1 holds two atomic drawing runs (EMF then WMF); inserting at
  // the first sits immediately before both.
  'image-emf-wmf': { paragraphPath: [0, 1], runIndex: 0, charOffset: 0 },
  // Paragraph 1's single atomic run holds the inline image.
  'image-inline': { paragraphPath: [0, 1], runIndex: 0, charOffset: 0 },
  // Paragraph 5 is the deepest-nested list item (`atlas-numbers`, level 2 —
  // lower-roman) — the construct most likely to have its `w:ilvl`/`w:numId`
  // silently flattened or dropped by a save.
  'lists-bullets-numbered': { paragraphPath: [0, 5], runIndex: 0, charOffset: 5 },
  // No in-body construct: `word/vbaProject.bin` is an unreferenced
  // package-level part. Paragraph 1 is this fixture's only real content.
  'macro-enabled-vba-project': { paragraphPath: [0, 1], runIndex: 0, charOffset: 2 },
  // Both real paragraphs (1 and 2) are a bare `w:oMath` parsed as a single
  // `UnknownNode` paragraph child, which `getEditableRuns` rejects outright
  // — see the "editor limitation" describe block below. Falls back to the
  // intro paragraph; there is no other paragraph in this fixture.
  'math-omml': INTRO_PARAGRAPH_START,
  // The page border and two-column layout are section properties with no
  // paragraph-level construct to aim inside; paragraph 1 is the paragraph
  // that actually flows through the two-column layout.
  'page-borders-columns': { paragraphPath: [0, 1], runIndex: 0, charOffset: 5 },
  // Paragraph 3 is this fixture's richest single construct: 7 runs mixing
  // bold/italic/underline. runIndex 1 lands inside the bold run ("bo|ld"),
  // splitting a formatted run rather than a plain one — the case most
  // likely to silently lose `w:rPr` on one side of the split.
  'plain-paragraphs-styles': { paragraphPath: [0, 3], runIndex: 1, charOffset: 2 },
  // Paragraph 2 is the mixed-direction paragraph; its runs flatten to
  // [rtl "مرحبا بالعالم", ltr " — mixed with ", ltr-bold "English", ltr "
  // text."]. runIndex 1 charOffset 0 lands exactly at the rtl/ltr boundary —
  // the position most likely to corrupt `w:rtl`/`w:bidi` on a save.
  'rtl-text': { paragraphPath: [0, 2], runIndex: 1, charOffset: 0 },
  // Section 0's block 2 is the empty paragraph whose mark carries the
  // section's own `w:sectPr` (the continuous-break boundary into section 1)
  // — an empty paragraph is still `insert-text`-editable (it takes the
  // "paragraph has zero editable runs" branch in `applyInsertText`), so this
  // inserts text directly into the sectPr-carrying paragraph itself.
  'section-breaks': { paragraphPath: [0, 2], runIndex: 0, charOffset: 0 },
  // [section 0, table (block 1), row 1, cell 0, its own paragraph 0] — the
  // `w:vMerge="restart"` cell ("Vertical merge start"), paired with row 2's
  // `w:vMerge="continue"` cell. Editing the restart cell's paragraph is the
  // case most likely to silently drop or flip the vertical merge.
  'table-fixed-grid-merged-cells': { paragraphPath: [0, 1, 1, 0, 0], runIndex: 0, charOffset: 8 },
  // [section 0, table (block 1), row 0, cell 0, its own paragraph 0] — the
  // header row cell ("Header A") the `w:tblStylePr[@w:type='firstRow']`
  // conditional formatting (bold + shading) actually applies to.
  'table-styled-banded': { paragraphPath: [0, 1, 0, 0, 0], runIndex: 0, charOffset: 3 },
  // Paragraph 1's runs flatten to [run "The quick ", ins-revision-run "brown
  // ", del-revision-run "" (zero-width — already-deleted text is a boundary,
  // not editable text), run "fox jumps..."]. runIndex 1 charOffset 3 lands
  // inside the tracked *insertion* itself ("bro|wn "), splitting a run that
  // is still wrapped in `w:ins` today.
  'tracked-changes-insert-delete': { paragraphPath: [0, 1], runIndex: 1, charOffset: 3 },
  // Paragraph 1 is the only body paragraph under the watermarked header; the
  // VML watermark shape itself lives in word/header1.xml, not reachable
  // through this command's body-only addressing.
  'watermark-header': { paragraphPath: [0, 1], runIndex: 0, charOffset: 4 },
}

interface KnownFailure {
  readonly mode: RoundtripMode
  readonly findingId: string
  readonly reason: string
}

// Failures already present on `main`, tracked against the finding that
// explains them. Remove an entry (promoting its test back to a plain `it`)
// once the underlying finding is fixed — the corresponding `it.fails` will
// itself start failing (because the assertions now pass) as a reminder.
//
// DXS-01 (header/footer/footnote/endnote parser stub) and DXS-02
// (w:tblGrid dropped on save) were both fixed by wave1/docx-save-integrity
// (P1.3, P1.5) — all four entries below were promoted back to plain `it`
// at that point; the round trips for these fixtures now pass.
const KNOWN_FAILURES: Partial<Record<FixtureId, ReadonlyArray<KnownFailure>>> = {}

async function produceSavedBytes(
  bundle: DocxBundle,
  mode: RoundtripMode,
  fixtureId: FixtureId,
): Promise<Uint8Array> {
  if (mode === 'no-op') {
    return saveDocx(bundle)
  }
  const edited = applyCommand(bundle.document, {
    kind: 'insert-text',
    at: EDIT_POSITIONS[fixtureId],
    text: 'EDITED: ',
  })
  return saveDocx({ ...bundle, document: edited.document })
}

async function assertRoundtrip(fixtureId: FixtureId, mode: RoundtripMode): Promise<void> {
  const originalBuffer = await readCorpusFixture(fixtureId)
  const originalPkg = await loadRawPackage(originalBuffer)

  const bundle = await loadDocx(originalBuffer)
  const savedBytes = await produceSavedBytes(bundle, mode, fixtureId)
  const resultPkg = await loadRawPackage(savedBytes)

  expect(findMalformedXmlParts(resultPkg), 'every XML/rels part must be well-formed').toEqual([])
  expect(
    findRelationshipProblems(resultPkg),
    'every relationship target must exist and have a content type',
  ).toEqual([])

  const owned = ownedPartPaths(originalPkg)
  expect(
    findPassthroughMismatches(originalPkg, resultPkg, owned),
    'parts Atlas does not own must survive a save byte-for-byte',
  ).toEqual([])

  const before = documentStructuralCounts(documentXmlOf(originalPkg))
  const after = documentStructuralCounts(documentXmlOf(resultPkg))
  expect(after, 'structural element counts and attribute-value fingerprint must be unchanged').toEqual(before)
}

describe('DOCX round-trip fidelity corpus (P0.5 / QA-09 / DXS-17)', () => {
  it('the corpus on disk matches the fixture ids this suite exercises', async () => {
    expect(await listCorpusFixtureIds()).toEqual([...FIXTURE_IDS].sort())
  })

  describe.each(FIXTURE_IDS)('%s', (fixtureId) => {
    const modes: ReadonlyArray<RoundtripMode> = ['no-op', 'trivial-edit']

    for (const mode of modes) {
      const knownFailure = KNOWN_FAILURES[fixtureId]?.find((failure) => failure.mode === mode)
      const title = knownFailure
        ? `${mode} round trip fails today (${knownFailure.findingId}: ${knownFailure.reason})`
        : `${mode} round trip`
      const runner = knownFailure ? it.fails : it

      runner(title, async () => {
        await assertRoundtrip(fixtureId, mode)
      })
    }
  })

  // FINDING (phase4/b4-corpus-tests, TEST-1), FIXED (INSERT-TEXT-THROWS-1) —
  // discovered while giving each corpus fixture its own trivial-edit
  // position: `applyInsertText`'s `getEditableRuns` (src/docx/editor/
  // commands.ts) used to reject a paragraph outright — `applyCommand` threw,
  // not just no-opped — the instant *any* of its children was a bookmark, a
  // comment range/reference, a footnote/endnote reference, or a bare
  // `w:oMath` (parsed as an `UnknownNode`). Typing in a paragraph that merely
  // contains a comment or a formula is a plausible everyday action, and it
  // used to throw (every caller `preventDefault()`s on a throw, so in the
  // real app this was a silently-discarded keystroke) instead of inserting
  // text around the construct. `applyInsertText` now partitions such a
  // paragraph via `chunkParagraphForInsert` into these inert markers (kept
  // byte-identical, never split or rewritten) and the genuinely editable
  // text around them, so typing elsewhere in the paragraph works and the
  // marker itself is untouched. These three tests, which used to assert the
  // throw (pinning the bug — see FIX-RULES.md's "never weaken a test"; this
  // corrects rather than weakens them), now assert the fixed behaviour:
  // insertion succeeds, the typed text lands where expected, and the
  // construct under test survives byte-for-byte.
  describe('insert-text reaches every construct, without disturbing it', () => {
    it("comments-with-reply: typing inside the commented run doesn't disturb the comment range/reference", async () => {
      const originalBuffer = await readCorpusFixture('comments-with-reply')
      const bundle = await loadDocx(originalBuffer)
      const before = (bundle.document.sections[0].blocks[1] as Paragraph).children

      // Editable-run index 1 is "commented phrase" (index 0 is the plain
      // lead-in run) — the `w:commentRangeStart`/`w:commentRangeEnd`/
      // `w:commentReference` markers around it are paragraph-level siblings,
      // not part of the flattened editable-run list.
      const result = applyCommand(bundle.document, {
        kind: 'insert-text',
        at: { paragraphPath: [0, 1], runIndex: 1, charOffset: 3 },
        text: 'X',
      })

      const after = (result.document.sections[0].blocks[1] as Paragraph).children
      expect(after.filter((c) => c.kind === 'comment-range')).toEqual(before.filter((c) => c.kind === 'comment-range'))
      expect(after.filter((c) => c.kind === 'comment-reference')).toEqual(
        before.filter((c) => c.kind === 'comment-reference'),
      )
      const editedRun = after.find(
        (c) => c.kind === 'run' && c.children.some((rc) => rc.kind === 'text' && rc.value.includes('X')),
      )
      expect(editedRun).toMatchObject({ children: [{ kind: 'text', value: 'comXmented phrase' }] })

      // Against the saved bytes, not just the in-memory model.
      const savedBytes = await saveDocx({ ...bundle, document: result.document })
      const savedPkg = await loadRawPackage(savedBytes)
      const savedXml = documentXmlOf(savedPkg)
      expect(savedXml).toContain('comXmented phrase')
      expect(savedXml).toMatch(/<w:commentRangeStart[^>]*w:id="1"/)
      expect(savedXml).toMatch(/<w:commentRangeEnd[^>]*w:id="1"/)
      expect(savedXml).toMatch(/<w:commentReference[^>]*w:id="1"/)
    })

    it("footnotes-endnotes: typing right after the footnote reference doesn't disturb it", async () => {
      const originalBuffer = await readCorpusFixture('footnotes-endnotes')
      const bundle = await loadDocx(originalBuffer)
      const before = (bundle.document.sections[0].blocks[1] as Paragraph).children
      const footnoteRefRunBefore = before[1]

      // Editable-run index 1 is the atomic run whose only child is the
      // `footnote-reference` — inserting at charOffset 0 there splices the
      // new text in as its own run immediately after it (the same
      // atomic-boundary-splice path an inline image already uses).
      const result = applyCommand(bundle.document, {
        kind: 'insert-text',
        at: { paragraphPath: [0, 1], runIndex: 1, charOffset: 0 },
        text: 'X',
      })

      const after = (result.document.sections[0].blocks[1] as Paragraph).children
      expect(after[1]).toEqual(footnoteRefRunBefore)
      expect(after[2]).toMatchObject({ kind: 'run', children: [{ kind: 'text', value: 'X' }] })

      const savedBytes = await saveDocx({ ...bundle, document: result.document })
      const savedPkg = await loadRawPackage(savedBytes)
      const savedXml = documentXmlOf(savedPkg)
      expect(savedXml).toMatch(/<w:footnoteReference[^>]*w:id="1"/)
      expect(savedXml).toContain('>X<')
    })

    it('math-omml: typing in an oMath-only paragraph appends text after the equation instead of dropping it', async () => {
      const originalBuffer = await readCorpusFixture('math-omml')
      const bundle = await loadDocx(originalBuffer)
      const before = (bundle.document.sections[0].blocks[1] as Paragraph).children
      expect(before).toHaveLength(1)
      expect(before[0].kind).toBe('unknown')

      const result = applyCommand(bundle.document, {
        kind: 'insert-text',
        at: { paragraphPath: [0, 1], runIndex: 0, charOffset: 0 },
        text: 'X',
      })

      const after = (result.document.sections[0].blocks[1] as Paragraph).children
      expect(after[0]).toEqual(before[0])
      expect(after[1]).toMatchObject({ kind: 'run', children: [{ kind: 'text', value: 'X' }] })

      const savedBytes = await saveDocx({ ...bundle, document: result.document })
      const savedPkg = await loadRawPackage(savedBytes)
      const savedXml = documentXmlOf(savedPkg)
      expect(savedXml).toContain('<m:oMath>')
      expect(savedXml).toContain('>X<')
    })
  })

  // D7 / DXP-06, DXL-08, DXS-05: the corpus's generic structural fingerprint
  // (paragraph/table/drawing/sectPr/tblGrid counts) doesn't inspect
  // styles.xml at all, so it alone can't catch "table style conditional
  // formatting silently dropped on save" — styles.xml is always rewritten
  // from Atlas's model (see index.ts's saveDocx), never passed through
  // byte-for-byte. This asserts the fixture's real `w:tblStylePr` blocks
  // (header-row bold+shading, band1Horz shading) survive a save.
  describe('table-styled-banded preserves w:tblStylePr on save (D7)', () => {
    it('keeps both conditional-formatting blocks, with their run/cell formatting intact', async () => {
      const originalBuffer = await readCorpusFixture('table-styled-banded')
      const bundle = await loadDocx(originalBuffer)
      const savedBytes = await saveDocx(bundle)
      const resultPkg = await loadRawPackage(savedBytes)

      const stylesXml = textOf(resultPkg, 'word/styles.xml')
      expect(stylesXml).toContain('w:tblStylePr')
      expect((stylesXml?.match(/<w:tblStylePr\b/g) ?? []).length).toBe(2)

      const reparsed = await loadDocx(Uint8Array.from(savedBytes).buffer)
      const style = reparsed.document.styles.get('AtlasBandedTable')

      expect(style?.conditionalFormats?.get('firstRow')).toMatchObject({
        run: { bold: true },
        cell: { shd: { fill: '4472C4' } },
      })
      expect(style?.conditionalFormats?.get('band1Horz')).toMatchObject({
        cell: { shd: { fill: 'D9E2F3' } },
      })
    })
  })

  // D4/DXS-09: `word/document.xml` is an owned/rewritten part, so the
  // generic round trip above (structural counts only) can't tell a correct
  // crop/rotation/flip round trip from one that silently zeroed them out
  // while keeping the same drawing count. This asserts the actual crop
  // rectangle and transform values survive a save unchanged.
  describe('image-crop-rotation-flip preserves crop/rotation/flip on save (DXS-09)', () => {
    it('keeps a:srcRect and a:xfrm rot/flipH values through a save + reparse', async () => {
      const originalBuffer = await readCorpusFixture('image-crop-rotation-flip')
      const bundle = await loadDocx(originalBuffer)

      const findDrawing = (doc: DocxBundle['document']) => {
        for (const block of doc.sections[0].blocks) {
          if (block.kind !== 'paragraph') continue
          for (const child of block.children) {
            if (child.kind !== 'run') continue
            for (const runChild of child.children) {
              if (runChild.kind === 'drawing') return runChild
            }
          }
        }
        return undefined
      }

      const original = findDrawing(bundle.document)
      expect(original).toMatchObject({
        crop: { l: 10000, t: 10000, r: 10000, b: 10000 },
        transform: { rotation: 1800000, flipH: true },
      })

      const savedBytes = await saveDocx(bundle)
      const reparsed = await loadDocx(Uint8Array.from(savedBytes).buffer)
      const roundTripped = findDrawing(reparsed.document)

      expect(roundTripped).toMatchObject({
        crop: { l: 10000, t: 10000, r: 10000, b: 10000 },
        transform: { rotation: 1800000, flipH: true },
      })
    })
  })

  // D19 / DXS-13: docProps/core.xml previously passed through byte-for-byte
  // (see `ownedPartPaths`'s D19 note above) — a save now regenerates its
  // modified date and last-modified-by rather than leaving whatever the
  // fixture's original author's last save wrote.
  describe('docProps/core.xml modified date + lastModifiedBy (D19 / DXS-13)', () => {
    it('regenerates dcterms:modified and cp:lastModifiedBy on every save', async () => {
      const originalBuffer = await readCorpusFixture('plain-paragraphs-styles')
      const originalPkg = await loadRawPackage(originalBuffer)
      const originalCoreXml = textOf(originalPkg, 'docProps/core.xml')
      expect(originalCoreXml).toContain('Atlas Corpus Generator')

      const bundle = await loadDocx(originalBuffer)
      const savedBytes = await saveDocx(bundle)
      const resultPkg = await loadRawPackage(savedBytes)
      const savedCoreXml = textOf(resultPkg, 'docProps/core.xml')

      expect(savedCoreXml).toBeDefined()
      expect(savedCoreXml).toContain('<cp:lastModifiedBy>Atlas</cp:lastModifiedBy>')
      expect(savedCoreXml).not.toContain('<cp:lastModifiedBy>Atlas Corpus Generator</cp:lastModifiedBy>')

      const modifiedMatch = savedCoreXml?.match(/<dcterms:modified[^>]*>([^<]+)<\/dcterms:modified>/)
      expect(modifiedMatch).not.toBeNull()
      expect(Date.now() - Date.parse(modifiedMatch![1])).toBeLessThan(60_000)

      // dc:creator (a distinct property from cp:lastModifiedBy) is untouched.
      expect(savedCoreXml).toContain('Atlas Corpus Generator')
    })
  })
})
