// DOCX round-trip fidelity corpus + harness (P0.5 / QA-09 / DXS-17).
//
// For every fixture in src/docx/__fixtures__/corpus/ (generated by
// scripts/generate-docx-corpus.mjs), exercises two round trips:
//   - "no-op": loadDocx -> saveDocx -> re-load, no changes.
//   - "trivial-edit": loadDocx -> insert text into the first paragraph via
//     the editor command API -> saveDocx -> re-load.
//
// Both assert: the saved package is a valid zip whose XML/rels parts are
// all well-formed; every internal relationship resolves to a part that
// exists and has a content type; every part Atlas doesn't intentionally
// rewrite is byte-identical to the original; and a small structural
// fingerprint of word/document.xml (paragraph/table/drawing/sectPr/tblGrid
// counts) is unchanged.
//
// A fixture+mode already known to fail (see the findings register at
// .sisyphus/plans/atlas-phase3-findings-register.md) is encoded as
// `it.fails` with its finding id in the title, so this suite is green today
// and flips red — telling whoever fixed it to promote the case back to
// `it` — the moment the underlying bug is fixed.
import { describe, expect, it } from 'vitest'

import { applyCommand } from '../editor'
import type { Position } from '../editor'
import { loadDocx, saveDocx } from '../index'
import type { DocxBundle } from '../index'
import {
  documentStructuralCounts,
  documentXmlOf,
  findMalformedXmlParts,
  findPassthroughMismatches,
  findRelationshipProblems,
  listCorpusFixtureIds,
  loadRawPackage,
  ownedPartPaths,
  readCorpusFixture,
  textOf,
} from './corpusRoundtripHelpers'

// Every fixture's body starts with one paragraph containing one plain run
// (see scripts/generate-docx-corpus.mjs's `introParagraph`), so this single
// position works as the trivial edit's insertion point for every fixture.
const FIRST_PARAGRAPH_START: Position = {
  paragraphPath: [0],
  runIndex: 0,
  charOffset: 0,
}

const FIXTURE_IDS = [
  'comments-with-reply',
  'content-control-alternate-content',
  'footnotes-endnotes',
  'header-footer-page-numbers',
  'hyperlinks-bookmarks',
  'image-anchored-floating',
  'image-crop-rotation-flip',
  'image-inline',
  'lists-bullets-numbered',
  'plain-paragraphs-styles',
  'section-breaks',
  'table-fixed-grid-merged-cells',
  'table-styled-banded',
  'tracked-changes-insert-delete',
] as const

type FixtureId = (typeof FIXTURE_IDS)[number]
type RoundtripMode = 'no-op' | 'trivial-edit'

interface KnownFailure {
  readonly mode: RoundtripMode
  readonly findingId: string
  readonly reason: string
}

// Failures already present on `main`, tracked against the finding that
// explains them. Remove an entry (promoting its test back to a plain `it`)
// once the underlying finding is fixed — the corresponding `it.fails` will
// itself start failing (because the assertions now pass) as a reminder.
//
// DXS-01 (header/footer/footnote/endnote parser stub) and DXS-02
// (w:tblGrid dropped on save) were both fixed by wave1/docx-save-integrity
// (P1.3, P1.5) — all four entries below were promoted back to plain `it`
// at that point; the round trips for these fixtures now pass.
const KNOWN_FAILURES: Partial<Record<FixtureId, ReadonlyArray<KnownFailure>>> = {}

async function produceSavedBytes(bundle: DocxBundle, mode: RoundtripMode): Promise<Uint8Array> {
  if (mode === 'no-op') {
    return saveDocx(bundle)
  }
  const edited = applyCommand(bundle.document, {
    kind: 'insert-text',
    at: FIRST_PARAGRAPH_START,
    text: 'EDITED: ',
  })
  return saveDocx({ ...bundle, document: edited.document })
}

async function assertRoundtrip(fixtureId: FixtureId, mode: RoundtripMode): Promise<void> {
  const originalBuffer = await readCorpusFixture(fixtureId)
  const originalPkg = await loadRawPackage(originalBuffer)

  const bundle = await loadDocx(originalBuffer)
  const savedBytes = await produceSavedBytes(bundle, mode)
  const resultPkg = await loadRawPackage(savedBytes)

  expect(findMalformedXmlParts(resultPkg), 'every XML/rels part must be well-formed').toEqual([])
  expect(
    findRelationshipProblems(resultPkg),
    'every relationship target must exist and have a content type',
  ).toEqual([])

  const owned = ownedPartPaths(originalPkg)
  expect(
    findPassthroughMismatches(originalPkg, resultPkg, owned),
    'parts Atlas does not own must survive a save byte-for-byte',
  ).toEqual([])

  const before = documentStructuralCounts(documentXmlOf(originalPkg))
  const after = documentStructuralCounts(documentXmlOf(resultPkg))
  expect(after, 'paragraph/table/drawing/sectPr/tblGrid counts must be unchanged').toEqual(before)
}

describe('DOCX round-trip fidelity corpus (P0.5 / QA-09 / DXS-17)', () => {
  it('the corpus on disk matches the fixture ids this suite exercises', async () => {
    expect(await listCorpusFixtureIds()).toEqual([...FIXTURE_IDS].sort())
  })

  describe.each(FIXTURE_IDS)('%s', (fixtureId) => {
    const modes: ReadonlyArray<RoundtripMode> = ['no-op', 'trivial-edit']

    for (const mode of modes) {
      const knownFailure = KNOWN_FAILURES[fixtureId]?.find((failure) => failure.mode === mode)
      const title = knownFailure
        ? `${mode} round trip fails today (${knownFailure.findingId}: ${knownFailure.reason})`
        : `${mode} round trip`
      const runner = knownFailure ? it.fails : it

      runner(title, async () => {
        await assertRoundtrip(fixtureId, mode)
      })
    }
  })

  // D7 / DXP-06, DXL-08, DXS-05: the corpus's generic structural fingerprint
  // (paragraph/table/drawing/sectPr/tblGrid counts) doesn't inspect
  // styles.xml at all, so it alone can't catch "table style conditional
  // formatting silently dropped on save" — styles.xml is always rewritten
  // from Atlas's model (see index.ts's saveDocx), never passed through
  // byte-for-byte. This asserts the fixture's real `w:tblStylePr` blocks
  // (header-row bold+shading, band1Horz shading) survive a save.
  describe('table-styled-banded preserves w:tblStylePr on save (D7)', () => {
    it('keeps both conditional-formatting blocks, with their run/cell formatting intact', async () => {
      const originalBuffer = await readCorpusFixture('table-styled-banded')
      const bundle = await loadDocx(originalBuffer)
      const savedBytes = await saveDocx(bundle)
      const resultPkg = await loadRawPackage(savedBytes)

      const stylesXml = textOf(resultPkg, 'word/styles.xml')
      expect(stylesXml).toContain('w:tblStylePr')
      expect((stylesXml?.match(/<w:tblStylePr\b/g) ?? []).length).toBe(2)

      const reparsed = await loadDocx(Uint8Array.from(savedBytes).buffer)
      const style = reparsed.document.styles.get('AtlasBandedTable')

      expect(style?.conditionalFormats?.get('firstRow')).toMatchObject({
        run: { bold: true },
        cell: { shd: { fill: '4472C4' } },
      })
      expect(style?.conditionalFormats?.get('band1Horz')).toMatchObject({
        cell: { shd: { fill: 'D9E2F3' } },
      })
    })
  })

  // D4/DXS-09: `word/document.xml` is an owned/rewritten part, so the
  // generic round trip above (structural counts only) can't tell a correct
  // crop/rotation/flip round trip from one that silently zeroed them out
  // while keeping the same drawing count. This asserts the actual crop
  // rectangle and transform values survive a save unchanged.
  describe('image-crop-rotation-flip preserves crop/rotation/flip on save (DXS-09)', () => {
    it('keeps a:srcRect and a:xfrm rot/flipH values through a save + reparse', async () => {
      const originalBuffer = await readCorpusFixture('image-crop-rotation-flip')
      const bundle = await loadDocx(originalBuffer)

      const findDrawing = (doc: DocxBundle['document']) => {
        for (const block of doc.sections[0].blocks) {
          if (block.kind !== 'paragraph') continue
          for (const child of block.children) {
            if (child.kind !== 'run') continue
            for (const runChild of child.children) {
              if (runChild.kind === 'drawing') return runChild
            }
          }
        }
        return undefined
      }

      const original = findDrawing(bundle.document)
      expect(original).toMatchObject({
        crop: { l: 10000, t: 10000, r: 10000, b: 10000 },
        transform: { rotation: 1800000, flipH: true },
      })

      const savedBytes = await saveDocx(bundle)
      const reparsed = await loadDocx(Uint8Array.from(savedBytes).buffer)
      const roundTripped = findDrawing(reparsed.document)

      expect(roundTripped).toMatchObject({
        crop: { l: 10000, t: 10000, r: 10000, b: 10000 },
        transform: { rotation: 1800000, flipH: true },
      })
    })
  })

  // D19 / DXS-13: docProps/core.xml previously passed through byte-for-byte
  // (see `ownedPartPaths`'s D19 note above) — a save now regenerates its
  // modified date and last-modified-by rather than leaving whatever the
  // fixture's original author's last save wrote.
  describe('docProps/core.xml modified date + lastModifiedBy (D19 / DXS-13)', () => {
    it('regenerates dcterms:modified and cp:lastModifiedBy on every save', async () => {
      const originalBuffer = await readCorpusFixture('plain-paragraphs-styles')
      const originalPkg = await loadRawPackage(originalBuffer)
      const originalCoreXml = textOf(originalPkg, 'docProps/core.xml')
      expect(originalCoreXml).toContain('Atlas Corpus Generator')

      const bundle = await loadDocx(originalBuffer)
      const savedBytes = await saveDocx(bundle)
      const resultPkg = await loadRawPackage(savedBytes)
      const savedCoreXml = textOf(resultPkg, 'docProps/core.xml')

      expect(savedCoreXml).toBeDefined()
      expect(savedCoreXml).toContain('<cp:lastModifiedBy>Atlas</cp:lastModifiedBy>')
      expect(savedCoreXml).not.toContain('<cp:lastModifiedBy>Atlas Corpus Generator</cp:lastModifiedBy>')

      const modifiedMatch = savedCoreXml?.match(/<dcterms:modified[^>]*>([^<]+)<\/dcterms:modified>/)
      expect(modifiedMatch).not.toBeNull()
      expect(Date.now() - Date.parse(modifiedMatch![1])).toBeLessThan(60_000)

      // dc:creator (a distinct property from cp:lastModifiedBy) is untouched.
      expect(savedCoreXml).toContain('Atlas Corpus Generator')
    })
  })
})
