/**
 * NEW-01 — verifies every blank "New Document" template committed under
 * `electron/templates/` (generated by `scripts/generate-templates.mjs`)
 * actually parses with Atlas's OWN parser for its format, and has the
 * expected minimal structure. These bytes are what a brand-new document (or
 * a 0-byte file of one of these formats — see `newDocumentTemplates.test.ts`
 * for that flow) hands straight to the real viewer, so a template that fails
 * to parse would break every new document of that format.
 */
import { readFileSync, readdirSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import * as XLSX from 'xlsx'

import { loadDocx, saveDocx } from '../docx'
import { loadOfficePackage, packageArchive } from '../office/officePackage'
import { parsePptxSlides } from '../viewers/slides/pptx/parser'
import { parseOdpSlides } from '../viewers/slides/odp/parser'
import { parseWorkbookBuffer } from '../viewers/shared/spreadsheetGrid'
import type { CancelSignal } from '../viewers/slides/shared/xmlUtils'

const TEMPLATES_DIR = path.resolve(__dirname, '../../electron/templates')

function readTemplate(name: string): ArrayBuffer {
  const buf = readFileSync(path.join(TEMPLATES_DIR, name))
  // `Uint8Array.from` copies into a fresh, exactly-sized ArrayBuffer (rather
  // than slicing Node's own possibly-pooled `Buffer.buffer`), avoiding a
  // cross-realm `ArrayBuffer` identity mismatch JSZip's type check rejects
  // under Vitest's jsdom environment.
  return Uint8Array.from(buf).buffer
}

describe('blank document templates', () => {
  it('electron/templates only contains the 5 known blank templates', () => {
    const files = readdirSync(TEMPLATES_DIR).sort()
    expect(files).toEqual(['blank.docx', 'blank.odp', 'blank.ods', 'blank.pptx', 'blank.xlsx'])
  })

  it('blank.docx parses with loadDocx as one empty paragraph, and re-saves cleanly', async () => {
    const bundle = await loadDocx(readTemplate('blank.docx'))
    expect(bundle.document.sections).toHaveLength(1)
    const section = bundle.document.sections[0]
    expect(section.blocks).toHaveLength(1)
    const [paragraph] = section.blocks
    expect(paragraph.kind).toBe('paragraph')

    // Round-trips through Atlas's own serializer with no thrown
    // DocxSaveError (the exact post-save validation DocxViewer's real Save
    // path runs — see `saveDocx`'s step 10).
    const resaved = await saveDocx(bundle)
    expect(resaved.byteLength).toBeGreaterThan(0)
  })

  it('blank.xlsx parses as one empty "Sheet1"', () => {
    const sheets = parseWorkbookBuffer(readTemplate('blank.xlsx'))
    expect(sheets).toHaveLength(1)
    expect(sheets[0].name).toBe('Sheet1')
    expect(
      sheets[0].grid.rows.length === 0 || sheets[0].grid.rows.every((row) => row.every((cell) => cell === '')),
    ).toBe(true)
  })

  it('blank.ods parses as one empty "Sheet1"', () => {
    const sheets = parseWorkbookBuffer(readTemplate('blank.ods'))
    expect(sheets).toHaveLength(1)
    expect(sheets[0].name).toBe('Sheet1')
  })

  it('blank.xlsx/blank.ods bytes are also plain SheetJS-readable (Office/Calc-compatible)', () => {
    for (const name of ['blank.xlsx', 'blank.ods']) {
      const wb = XLSX.read(new Uint8Array(readTemplate(name)), { type: 'array' })
      expect(wb.SheetNames).toEqual(['Sheet1'])
    }
  })

  it('blank.pptx parses as one 16:9 slide with an empty title placeholder', async () => {
    const pkg = await loadOfficePackage(readTemplate('blank.pptx'))
    const archive = packageArchive(pkg)
    const signal: CancelSignal = { cancelled: false }
    const slides = await parsePptxSlides(archive, signal)

    expect(slides).toHaveLength(1)
    expect(slides[0].error).toBeUndefined()
    expect(slides[0].width).toBe(1280)
    expect(slides[0].height).toBe(720)
    expect(slides[0].shapes.length).toBeGreaterThan(0)
  })

  it('blank.odp parses as one 16:9 slide with an empty title frame', async () => {
    const pkg = await loadOfficePackage(readTemplate('blank.odp'))
    const archive = packageArchive(pkg)
    const signal: CancelSignal = { cancelled: false }
    const slides = await parseOdpSlides(archive, signal)

    expect(slides).toHaveLength(1)
    expect(slides[0].error).toBeUndefined()
    expect(slides[0].width).toBe(1280)
    expect(slides[0].height).toBe(720)
  })
})
