// Pure generation helpers for the extension manifest (P2.2 / ELEC-05,
// ELEC-15, LOAD-03, LOAD-12). Shared between the CLI script
// (scripts/generate-extension-manifest.mjs) and its regression test
// (src/formats/__tests__/extensionManifest.test.ts) so the test can assert
// the two generated artifacts on disk are byte-for-byte what the manifest
// would produce, without shelling out to the CLI script itself.

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/generate-extension-manifest.mjs from\n' +
  '// src/formats/extensionManifest.ts — do not edit by hand. Edit the\n' +
  '// manifest and run `npm run generate:extensions` (or `npm run build`,\n' +
  '// which does this automatically via the `prebuild` script).\n' +
  "'use strict';\n\n"

/**
 * @param {ReadonlyArray<{ ext: string }>} manifest
 * @returns {string[]}
 */
export function buildExtensionList(manifest) {
  return [...new Set(manifest.map((entry) => entry.ext))].sort()
}

/**
 * @param {ReadonlyArray<{ ext: string }>} manifest
 * @returns {string}
 */
export function buildGeneratedCjsSource(manifest) {
  const extensions = buildExtensionList(manifest)
  const listLiteral = JSON.stringify(extensions, null, 2).replace(/\n/g, '\n  ')

  return `${GENERATED_HEADER}module.exports = {\n  EXTENSIONS: ${listLiteral},\n};\n`
}

const YAML_ITEM_INDENT = '    '
const YAML_FIELD_INDENT = '      '

/**
 * electron-builder's YAML config only needs plain-scalar quoting when a value isn't a bare word/sentence.
 * @param {string} value
 * @returns {string}
 */
function yamlScalar(value) {
  return /^[\w][\w .,()/-]*$/.test(value) ? value : JSON.stringify(value)
}

/**
 * @param {ReadonlyArray<{ ext: string; associationName: string; associationDescription: string; associationRole: string }>} manifest
 * @returns {string}
 */
export function buildYamlAssociationsBlock(manifest) {
  return manifest
    .map((entry) =>
      [
        `${YAML_ITEM_INDENT}- ext: ${entry.ext}`,
        `${YAML_FIELD_INDENT}name: ${yamlScalar(entry.associationName)}`,
        `${YAML_FIELD_INDENT}description: ${yamlScalar(entry.associationDescription)}`,
        `${YAML_FIELD_INDENT}role: ${entry.associationRole}`,
      ].join('\n'),
    )
    .join('\n')
}

export const YAML_BEGIN_MARKER =
  '    # BEGIN GENERATED FILE ASSOCIATIONS — scripts/generate-extension-manifest.mjs (source: src/formats/extensionManifest.ts). Do not edit by hand; edit the manifest and run `npm run generate:extensions`.'
export const YAML_END_MARKER = '    # END GENERATED FILE ASSOCIATIONS'

/**
 * Replaces the associations list between the two sentinel comments in an
 * electron-builder.yml source string, leaving everything else untouched.
 * @param {string} ymlText
 * @param {string} block
 * @returns {string}
 */
export function spliceYamlAssociations(ymlText, block) {
  const beginIndex = ymlText.indexOf(YAML_BEGIN_MARKER)
  const endIndex = ymlText.indexOf(YAML_END_MARKER)

  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new Error(
      'electron-builder.yml is missing the generated-associations sentinel comments — cannot regenerate fileAssociations safely.',
    )
  }

  const before = ymlText.slice(0, beginIndex + YAML_BEGIN_MARKER.length)
  const after = ymlText.slice(endIndex)

  return `${before}\n${block}\n${after}`
}
