// NEW-01 — the single source of truth, in main, for:
//   1. which document formats Atlas's "New" toolbar action/menu can create
//      (a fixed, main-owned list — the renderer only ever sends a format
//      *name*, never a path or template bytes, over IPC — see `main.cjs`'s
//      `document:new` handler), and
//   2. which of those formats have a pre-built blank binary template under
//      `electron/templates/` (generated by `scripts/generate-templates.mjs`
//      — see that script's header for how each one was built) versus just
//      an empty string (markdown has no meaningful "blank template" file;
//      an empty `.md` is already a valid empty markdown document).
//
// Reused by two flows:
//   - `document:new` (electron/main.cjs) — write a fresh copy of the
//     template to a user-chosen path.
//   - the "open a 0-byte file of an editable format" flow (same file) —
//     substitutes the matching blank template's bytes for the empty read,
//     so the file behaves exactly like a freshly created document, still
//     bound to its own (empty-on-disk) path, and a normal Save fills it in.
const fs = require('fs');
const path = require('path');

const TEMPLATES_DIR = path.join(__dirname, '..', 'templates');

/**
 * @typedef {{
 *   readonly extension: string,
 *   readonly defaultName: string,
 *   readonly filterName: string,
 *   readonly templateFile: string | null,
 * }} NewDocumentFormatSpec
 */

// Only formats with a real, wired-up in-app editor (DocxViewer, the
// spreadsheet editor behind XlsxViewer/OdsViewer, the PPTX/ODP slide
// editors, and markdown's own RawEditor/save path — see the P1.1 document-
// session `registerSave` contract each one plugs into) are offered here.
// Plain-text/code files (CodeViewer) and CSV/TSV are editable too but are
// deliberately left off both this list and the toolbar's "New" menu — the
// owner's plan named the docx/xlsx/pptx/markdown set explicitly, and CSV/TSV
// have no natural "blank template" distinct from an empty markdown file.
/** @type {Readonly<Record<string, NewDocumentFormatSpec>>} */
const NEW_DOCUMENT_FORMATS = {
  markdown: { extension: 'md', defaultName: 'Document.md', filterName: 'Markdown', templateFile: null },
  docx: { extension: 'docx', defaultName: 'Document.docx', filterName: 'Word Document', templateFile: 'blank.docx' },
  xlsx: { extension: 'xlsx', defaultName: 'Workbook.xlsx', filterName: 'Excel Workbook', templateFile: 'blank.xlsx' },
  ods: {
    extension: 'ods',
    defaultName: 'Spreadsheet.ods',
    filterName: 'OpenDocument Spreadsheet',
    templateFile: 'blank.ods',
  },
  pptx: {
    extension: 'pptx',
    defaultName: 'Presentation.pptx',
    filterName: 'PowerPoint Presentation',
    templateFile: 'blank.pptx',
  },
  odp: {
    extension: 'odp',
    defaultName: 'Presentation.odp',
    filterName: 'OpenDocument Presentation',
    templateFile: 'blank.odp',
  },
};

/** Extension (no dot, lowercase) -> template file name, derived from the table above. */
const TEMPLATE_FILE_BY_EXTENSION = Object.fromEntries(
  Object.values(NEW_DOCUMENT_FORMATS)
    .filter((spec) => spec.templateFile)
    .map((spec) => [spec.extension, spec.templateFile]),
);

/** @type {Map<string, Buffer>} */
const templateCache = new Map();

/**
 * @param {string} templateFile
 * @returns {Buffer}
 */
function readTemplateBytes(templateFile) {
  let bytes = templateCache.get(templateFile);
  if (!bytes) {
    bytes = fs.readFileSync(path.join(TEMPLATES_DIR, templateFile));
    templateCache.set(templateFile, bytes);
  }
  return bytes;
}

/**
 * The blank template bytes for `filePath`'s extension, or `null` when that
 * extension has none (not a re-templatable format, or the template is
 * missing/unreadable — callers fall back to the original empty read).
 * @param {string} filePath
 * @returns {Buffer | null}
 */
function templateBytesForExtension(filePath) {
  const ext = path.extname(filePath).slice(1).toLowerCase();
  const templateFile = TEMPLATE_FILE_BY_EXTENSION[ext];
  if (!templateFile) return null;
  try {
    return readTemplateBytes(templateFile);
  } catch {
    return null;
  }
}

module.exports = { NEW_DOCUMENT_FORMATS, templateBytesForExtension, readTemplateBytes };
